title: Miri Robot Fortune Teller
logo: /assets/img/logo.jpg
description: A bot provides different divination and fortune-telling methods. The development is still progressing...
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
